use crate::error::AppResult;
use crate::models::{EscalationInput, Template};
use handlebars::Handlebars;
use serde_json::json;

const TEMPLATE: &str = r#"## Escalation: {{ticket_id}}
{{#if template_name}}**Template:** {{template_name}}{{/if}}

### Problem Summary
{{problem_summary}}

### Troubleshooting Steps
{{#each checklist}}
- [{{#if checked}}x{{else}} {{/if}}] {{text}}
{{/each}}

### Current Status
{{current_status}}

### Next Steps
{{next_steps}}

{{#if llm_summary}}
### AI Summary
{{llm_summary}}
(Confidence: {{llm_confidence}})
{{/if}}

---
*Generated by Ticket Handoff Assistant*
"#;

pub fn render_markdown(template: Option<&Template>, input: &EscalationInput) -> AppResult<String> {
    let mut handlebars = Handlebars::new();
    handlebars.register_template_string("escalation", TEMPLATE)?;

    let data = json!({
        "ticket_id": input.ticket_id,
        "template_name": template.map(|t| &t.name),
        "problem_summary": input.problem_summary,
        "checklist": input.checklist,
        "current_status": input.current_status,
        "next_steps": input.next_steps,
        "llm_summary": input.llm_summary,
        "llm_confidence": input.llm_confidence,
    });

    let rendered = handlebars.render("escalation", &data)?;
    Ok(rendered)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::ChecklistItem;

    #[test]
    fn test_render_markdown() {
        let input = EscalationInput {
            ticket_id: "TEST-123".to_string(),
            template_id: None,
            problem_summary: "User cannot access VPN".to_string(),
            checklist: vec![
                ChecklistItem { text: "Restarted VPN client".to_string(), checked: true },
                ChecklistItem { text: "Verified credentials".to_string(), checked: false },
            ],
            current_status: "VPN still not connecting".to_string(),
            next_steps: "Check firewall settings".to_string(),
            llm_summary: None,
            llm_confidence: None,
        };

        let result = render_markdown(None, &input);
        assert!(result.is_ok());

        let markdown = result.unwrap();
        assert!(markdown.contains("TEST-123"));
        assert!(markdown.contains("User cannot access VPN"));
        assert!(markdown.contains("- [x] Restarted VPN client"));
        assert!(markdown.contains("- [ ] Verified credentials"));
    }
}
